name: .NET Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-cross-platform:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}
    name: Test on ${{matrix.os}}

    defaults:
      run:
        working-directory: .src

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.302

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release
      
    - name: Execute unit tests
      run: dotnet test --no-build --configuration Release
